namespace ProjectEulerNet
{
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    internal class Problem002 : IProblem
    {
        public object Solve()
        {
            long sum = 2;

            var first = 1;
            var second = 2;
            var current = first + second;

            while(current < 4000000)
            {
                if(current % 2 == 0)
                    sum += current;

                first = second;
                second = current;
                current = first + second;
            }
            return sum;
        }
    }
}